{
  "news": {
    "ai-news": "AI新闻",
    "tech-news": "技术新闻",
    "industry-news": "行业动态"
  },
  "tools": {
    "general-cn": "国内通用工具",
    "general-overseas": "海外通用工具",
    "painting": "AI绘画工具",
    "coding": "编程工具",
    "voice": "语音工具",
    "video": "视频工具",
    "modeling": "建模工具",
    "security": "安全工具",
    "agent": "智能代理",
    "other": "其他工具"
  },
  "tutorials": {
    "prompts": "提示词教程",
    "courses": "课程内容",
    "deeplearning": "深度学习"
  }
}