name: Trigger Frontend Build

on:
  push:
    branches: [main]

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger frontend build
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/username/frontend-repo/dispatches \
          -d '{"event_type":"content-updated"}' 