name: Validate Content

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
    
    - name: Validate content
      run: npm run validate
      continue-on-error: true
    
    - name: Format check
      run: npm run format -- --check
      continue-on-error: true
    
    - name: Lint markdown
      run: npm run lint
      continue-on-error: true 